version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ./MongoDB:/data/db
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - "8081:8081"
  
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: ./Back-End
    env_file:
      - .env
    volumes:
      - ./Back-End:/app
    ports: 
      - "8080:8080"
